<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="8" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-12T12:42:54 IST" name="Default suite" finished-at="2023-06-12T12:43:16 IST" duration-ms="21607">
    <groups>
    </groups>
    <test started-at="2023-06-12T12:42:54 IST" name="Default test" finished-at="2023-06-12T12:43:16 IST" duration-ms="21607">
      <class name="com.share.testcase.BankManagerLoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.share.testcase.BankManagerLoginTest@6aecbb8d]" started-at="2023-06-12T12:42:52 IST" name="setUp" finished-at="2023-06-12T12:42:54 IST" duration-ms="2305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginasBankManager()[pri:0, instance:com.share.testcase.BankManagerLoginTest@6aecbb8d]" started-at="2023-06-12T12:42:54 IST" name="loginasBankManager" finished-at="2023-06-12T12:42:57 IST" duration-ms="3095" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not successfull]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not successfull
at org.testng.Assert.fail(Assert.java:110)
at com.share.testcase.BankManagerLoginTest.loginasBankManager(BankManagerLoginTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginasBankManager -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.share.testcase.BankManagerLoginTest@6aecbb8d]" started-at="2023-06-12T12:43:16 IST" name="tearDown" finished-at="2023-06-12T12:43:16 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.share.testcase.BankManagerLoginTest -->
      <class name="com.share.testcase.AddCustomerTest">
        <test-method signature="addCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.share.testcase.AddCustomerTest@60a2630a]" started-at="2023-06-12T12:42:57 IST" name="addCustomer" data-provider="getData" finished-at="2023-06-12T12:43:16 IST" duration-ms="18466" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bhautikaa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[radaadiyaa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0101agggttt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- com.share.testcase.AddCustomerTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
